#pragma once
#include "pch.h"

class cGcUniverseAddressData;
class cGcUniverseAddressData;
class cGcDifficultyStateData;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcByteBeatLibraryData;
class cGcInventoryContainer;
class cGcUniverseAddressData;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcResourceElement;
class cGcExactResource;
class cGcInteractionData;
class cGcInteractionData;
class cGcInteractionData;
class cGcUniverseAddressData;
class cGcUniverseAddressData;
class cGcResourceElement;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcUniverseAddressData;
class cGcTerrainEditsBuffer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcResourceElement;
class cGcPortalSaveData;
class cGcTeleportEndpoint;
class cGcPlayerWeapons;
class cGcPlayerWeapons;
class cGcUniverseAddressData;
class cGcPlayerSpawnStateData;
class cGcUniverseAddressData;
class cGcPhotoModeSettings;
class cGcSeasonalGameModeData;
class cGcSeasonStateData;

class cGcPlayerStateData
{
public:
    static const unsigned __int64 muNameHash = 0x6C4510BB243EFA64;
    static const unsigned __int64 muTemplateHash = 0x8FEEE8175F5670DD;
    static const int miNumMembers = 227;

    cGcUniverseAddressData mUniverseAddress;
    cGcUniverseAddressData mPreviousUniverseAddress;
    int miHomeRealityIteration;
    cTkFixedString<128,char> macSaveName;
    cTkFixedString<128,char> macSaveSummary;
    cGcDifficultyStateData mDifficultyState;
    cGcInventoryContainer mInventory;
    cGcInventoryContainer mInventory_TechOnly;
    cGcInventoryContainer mInventory_Cargo;
    cGcInventoryContainer mShipInventory;
    cGcInventoryContainer mWeaponInventory;
    cTkFixedArray<cGcMultitoolData, 6> maMultitools;
    int miActiveMultioolIndex;
    cGcByteBeatLibraryData mByteBeatLibrary;
    cTkFixedArray<cGcPetData, 18> maPets;
    cTkFixedArray<cGcPetData, 18> maEggs;
    cTkFixedArray<cGcPetCustomisationData, 18> maPetAccessoryCustomisation;
    cTkFixedArray<bool, 18> maUnlockedPetSlots;
    cGcInventoryContainer mGraveInventory;
    bool mbSpawnGrave;
    bool mbSpaceGrave;
    cGcUniverseAddressData mGraveUniverseAddress;
    cTkVector4 mGravePosition;
    cTkVector4 mGraveMatrixLookAt;
    cTkVector4 mGraveMatrixUp;
    cGcInventoryLayout mShipLayout;
    cGcInventoryLayout mWeaponLayout;
    cGcResourceElement mCurrentShip;
    cGcExactResource mCurrentWeapon;
    cTkDynamicArray<TkID<128>1> maKnownTech;
    cTkDynamicArray<TkID<128>1> maKnownProducts;
    cTkDynamicArray<TkID<128>1> maKnownSpecials;
    cTkDynamicArray<TkID<256>1> maKnownRefinerRecipes;
    cTkDynamicArray<cGcWordKnowledge1> maKnownWords;
    cTkDynamicArray<cGcWordGroupKnowledge1> maKnownWordGroups;
    cTkDynamicArray<cGcPlayerMissionProgress1> maMissionProgress;
    int miPostMissionIndex;
    TkID<128> mCurrentMissionID;
    unsigned __int64 mui64CurrentMissionSeed;
    TkID<128> mPreviousMissionID;
    unsigned __int64 mui64PreviousMissionSeed;
    int miMissionVersion;
    cTkDynamicArray<cGcMissionIDEpochPair1> maMissionRecurrences;
    cGcInteractionData mHoloExplorerInteraction;
    cGcInteractionData mHoloScepticInteraction;
    cGcInteractionData mHoloNooneInteraction;
    int miHealth;
    int miShipHealth;
    int miShield;
    int miShipShield;
    int miEnergy;
    int miUnits;
    int miNanites;
    int miSpecials;
    bool mbThirdPersonShip;
    unsigned __int64 mui64TimeAlive;
    unsigned __int64 mui64TotalPlayTime;
    cTkDynamicArray<cGcScanEventSave1> maMarkerStack;
    cTkDynamicArray<cGcScanEventSave1> maNewMPMarkerStack;
    cTkDynamicArray<cTkVector31> maSurveyedEventPositions;
    int miNextSurveyedEventPositionIndex;
    cTkDynamicArray<cGcPlayerStatsGroup1> maStats;
    cTkDynamicArray<cGcTelemetryStat1> maTelemetryStats;
    cTkFixedArray<cGcInteractionBuffer, 11> maStoredInteractions;
    cTkDynamicArray<cGcMaintenanceContainer1> maMaintenanceInteractions;
    cTkDynamicArray<cGcMaintenanceContainer1> maPersonalMaintenanceInteractions;
    cTkDynamicArray<unsigned __int641> maVisitedSystems;
    cTkFixedArray<float, 6> maHazard;
    int miBoltAmmo;
    int miScatterAmmo;
    int miPulseAmmo;
    int miLaserAmmo;
    cTkVector4 mFirstSpawnPosition;
    cTkFixedArray<cGcSavedInteractionRaceData, 131> maSavedInteractionIndicies;
    cTkDynamicArray<cGcSavedInteractionDialogData1> maSavedInteractionDialogTable;
    cTkDynamicArray<TkID<256>1> maInteractionProgressTable;
    cTkFixedArray<cGcUniverseAddressData, 10> maAtlasStationAdressData;
    cTkFixedArray<cGcUniverseAddressData, 11> maNewAtlasStationAdressData;
    cTkDynamicArray<cGcUniverseAddressData1> maVisitedAtlasStationsData;
    bool mbFirstAtlasStationDiscovered;
    bool mbUsesThirdPersonCharacterCam;
    int miProgressionLevel;
    int miProcTechIndex;
    bool mbIsNew;
    bool mbUseSmallerBlackholeJumps;
    cTkDynamicArray<cGcSavedEntitlement1> maUsedEntitlements;
    cTkFixedArray<cTkVector3, 16> maPlanetPositions;
    cTkFixedArray<cTkSeed, 16> maPlanetSeeds;
    int miPrimaryPlanet;
    unsigned __int64 mui64TimeLastSpaceBattle;
    int miWarpsLastSpaceBattle;
    unsigned __int64 mui64ActiveSpaceBattleUA;
    unsigned __int64 mui64TimeLastMiniStation;
    int miWarpsLastMiniStation;
    unsigned __int64 mui64MiniStationUA;
    cTkVector4 mAnomalyPositionOverride;
    cGcUniverseAddressData mGameStartAddress1;
    cGcUniverseAddressData mGameStartAddress2;
    cTkFixedArray<bool, 16> maGalacticMapRequests;
    cTkVector4 mFirstShipPosition;
    unsigned __int64 mui64HazardTimeAlive;
    bool mbRevealBlackHoles;
    cTkSeed mCurrentFreighterHomeSystemSeed;
    cGcResourceElement mCurrentFreighter;
    cGcInventoryLayout mFreighterLayout;
    cGcInventoryLayout mFreighterCargoLayout;
    cGcInventoryContainer mFreighterInventory;
    cGcInventoryContainer mFreighterInventory_TechOnly;
    cGcInventoryContainer mFreighterInventory_Cargo;
    unsigned __int64 mui64FreighterLastSpawnTime;
    cGcUniverseAddressData mFreighterUniverseAddress;
    bool mbFreighterDismissed;
    cTkVector3 mFreighterMatrixAt;
    cTkVector3 mFreighterMatrixUp;
    cTkVector3 mFreighterMatrixPos;
    cTkFixedArray<bool, 4> maSquadronUnlockedPilotSlots;
    cTkFixedArray<cGcSquadronPilotData, 4> maSquadronPilots;
    cTkDynamicArray<TkID<128>1> maSeenBaseBuildingObjects;
    cTkDynamicArray<cGcPersistentBBObjectData1> maBaseBuildingObjects;
    cGcTerrainEditsBuffer mTerrainEditData;
    cTkFixedArray<cGcNPCWorkerData, 5> maNPCWorkers;
    cTkDynamicArray<cGcPersistentBase1> maPersistentPlayerBases;
    cTkDynamicArray<cGcTeleportEndpoint1> maTeleportEndpoints;
    cGcInventoryLayout mChest1Layout;
    cGcInventoryContainer mChest1Inventory;
    cGcInventoryLayout mChest2Layout;
    cGcInventoryContainer mChest2Inventory;
    cGcInventoryLayout mChest3Layout;
    cGcInventoryContainer mChest3Inventory;
    cGcInventoryLayout mChest4Layout;
    cGcInventoryContainer mChest4Inventory;
    cGcInventoryLayout mChest5Layout;
    cGcInventoryContainer mChest5Inventory;
    cGcInventoryLayout mChest6Layout;
    cGcInventoryContainer mChest6Inventory;
    cGcInventoryLayout mChest7Layout;
    cGcInventoryContainer mChest7Inventory;
    cGcInventoryLayout mChest8Layout;
    cGcInventoryContainer mChest8Inventory;
    cGcInventoryLayout mChest9Layout;
    cGcInventoryContainer mChest9Inventory;
    cGcInventoryLayout mChest10Layout;
    cGcInventoryContainer mChest10Inventory;
    cGcInventoryLayout mChestMagicLayout;
    cGcInventoryContainer mChestMagicInventory;
    cGcInventoryLayout mChestMagic2Layout;
    cGcInventoryContainer mChestMagic2Inventory;
    cGcInventoryLayout mCookingIngredientsLayout;
    cGcInventoryContainer mCookingIngredientsInventory;
    cGcInventoryLayout mRocketLockerLayout;
    cGcInventoryContainer mRocketLockerInventory;
    cGcResourceElement mCurrentFreighterNPC;
    cTkFixedArray<cGcPlayerOwnershipData, 7> maVehicleOwnership;
    int miPrimaryVehicle;
    cTkFixedArray<cGcPlayerOwnershipData, 12> maShipOwnership;
    int miPrimaryShip;
    bool mbMultiShipEnabled;
    bool mbVehicleAIControlEnabled;
    cTkFixedString<32,char> macPlayerFreighterName;
    cTkVector4 mStartGameShipPosition;
    bool mbShipNeedsTerrainPositioning;
    int miTradingSupplyDataIndex;
    cTkDynamicArray<cGcTradingSupplyData1> maTradingSupplyData;
    cTkDynamicArray<cGcPortalSaveData1> maLastPortal;
    cGcPortalSaveData mVisitedPortal;
    int miKnownPortalRunes;
    bool mbOnOtherSideOfPortal;
    cGcTeleportEndpoint mOtherSideOfPortalReturnBase;
    cTkVector4 mPortalMarkerPosition_Local;
    cTkVector4 mPortalMarkerPosition_Offset;
    cGcPlayerWeapons mStartingPrimaryWeapon;
    cGcPlayerWeapons mStartingSecondaryWeapon;
    cTkFixedArray<cGcCharacterCustomisationSaveData, 23> maCharacterCustomisationData;
    cTkFixedArray<bool, 12> maShipUsesLegacyColours;
    cTkFixedArray<cGcCharacterCustomisationData, 3> maOutfits;
    TkID<128> mJetpackEffect;
    TkID<128> mFreighterEngineEffect;
    cTkSeed mFleetSeed;
    cTkDynamicArray<cGcFleetFrigateSaveData1> maFleetFrigates;
    cTkDynamicArray<cGcFleetExpeditionSaveData1> maFleetExpeditions;
    cTkDynamicArray<unsigned __int641> maExpeditionSeedsSelectedToday;
    unsigned __int64 mui64LastKnownDay;
    unsigned __int64 mui64SunTimer;
    unsigned __int64 mui64MultiplayerLobbyID;
    cGcUniverseAddressData mMultiplayerUA;
    cGcPlayerSpawnStateData mMultiplayerSpawn;
    cTkDynamicArray<cGcRepairTechData1> maRepairTechBuffer;
    unsigned __int64 mui64MultiplayerPrivileges;
    cTkFixedArray<cGcHotActionsSaveData, 3> maHotActions;
    unsigned __int64 mui64LastUABeforePortalWarp;
    unsigned __int64 mui64StoryPortalSeed;
    unsigned __int16 muiShopNumber;
    unsigned __int16 muiShopTier;
    bool mbHasAccessToNexus;
    cGcUniverseAddressData mNexusUniverseAddress;
    cTkVector3 mNexusMatrixAt;
    cTkVector3 mNexusMatrixUp;
    cTkVector3 mNexusMatrixPos;
    cGcPhotoModeSettings mPhotoModeSettings;
    int miBannerIcon;
    int miBannerMainColour;
    int miBannerBackgroundColour;
    TkID<128> mBannerTitleId;
    int miTelemetryUploadVersion;
    bool mbUsesThirdPersonVehicleCam;
    float mfVRCameraOffset;
    cGcSeasonalGameModeData mSeasonData;
    cGcSeasonStateData mSeasonState;
    bool mbRestartAllInactiveSeasonalMissions;
    cTkDynamicArray<TkID<128>1> maRedeemedSeasonRewards;
    cTkDynamicArray<TkID<128>1> maRedeemedTwitchRewards;
    cTkDynamicArray<TkID<128>1> maRedeemedPlatformRewards;
    cTkFixedArray<cGcSettlementState, 100> maSettlementStatesV2;
    int miSettlementStateRingBufferIndexV2;
    bool mbNextLoadSpawnsWithFreshStart;
    cTkFixedArray<cGcStoryPageSeenDataArray, 8> maSeenStories;
    cTkFixedArray<cGcWonderRecord, 11> maWonderPlanetRecords;
    cTkFixedArray<cGcWonderRecord, 15> maWonderCreatureRecords;
    cTkFixedArray<cGcWonderRecord, 8> maWonderFloraRecords;
    cTkFixedArray<cGcWonderRecord, 8> maWonderMineralRecords;
    cTkFixedArray<cGcWonderRecord, 13> maWonderTreasureRecords;
    cTkFixedArray<cGcWonderRecord, 11> maWonderWeirdBasePartRecords;
    cTkFixedArray<cGcWonderRecord, 12> maWonderCustomRecords;
    cTkFixedArray<cGcWonderRecordCustomData, 12> maWonderCustomRecordsExtraData;
    cTkFixedArray<cGcSyncBufferSaveDataArray, 4> maSyncBuffersData;
    cTkDynamicArray<cGcMaintenanceSaveKey1> maRefinerBufferKeys;
    cTkDynamicArray<cGcMaintenanceContainer1> maRefinerBufferData;

    static bool ClassPointerCompare(const cTkClassPointer* lPtr, const cTkClassPointer *lOtherPtr);
    static void ClassPointerCopy(cTkClassPointer* lDest, const cTkClassPointer *lSource);
    static cTkClassPointer* ClassPointerCreate(cTkClassPointer* result);
    static void ClassPointerCreateDefault(cTkClassPointer* lPtr, cTkLinearMemoryPool* lpAllocator);
    static void ClassPointerDestroy(cTkClassPointer* lPtr);
    static void ClassPointerValidateData(cTkClassPointer* lPtr);
    static unsigned __int64 ClassPointerGenerateHash(const cTkClassPointer* lPtr, unsigned __int64 luHash, bool lbDeep);
    static void ClassPointerRead(cTkClassPointer* lPtr, XMLNode* lDataNode, cTkLinearMemoryPool* lpAllocator);
    static void ClassPointerRender(cTkClassPointer* lPtr);
    static bool ClassPointerSave(const cTkClassPointer* lPtr, const char* lpacFilename);
    static void ClassPointerWrite(const cTkClassPointer* lPtr, XMLNode* lDataNode, bool lbForceShortForm);
};
