#pragma once

#include "../../../../../../pch.h"
class cGcGameMode;
class cGcDifficultyPresetType;
class cGcDifficultySettingsData;
class cTkTextureResource;
class cGcSpaceshipClasses;
class cGcAlienRace;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcInventoryContainer;
class cGcScanEventTable;
class cGcTradeData;

class cGcSeasonalGameModeData
{
    static const unsigned __int64 muNameHash = 18260702183926367749;
    static const unsigned __int64 muTemplateHash = 11874102268242930343;
    static const int miNumMembers = 88;

    int miSeasonId;
    unsigned __int64 mui64StartTimeUTC;
    unsigned __int64 mui64EndTimeUTC;
    unsigned __int64 mui64Hash;
    cTkFixedString<32,char> macTitle;
    cTkFixedString<32,char> macSubtitle;
    cTkFixedString<32,char> macDescription;
    TkID<256> mFinalStageTitle;
    TkID<256> mMilestoneWithStageLocId;
    cGcGameMode mGameMode;
    cGcDifficultyPresetType mDifficultySettingPreset;
    cGcDifficultySettingsData mDifficultyMinimums;
    cTkFixedString<32,char> macSeasonalUAOverride;
    unsigned __int64 mui64UAOverrideValue;
    TkID<128> mFinalReward;
    TkID<128> mFinalRewardSwitchAlt;
    TkID<256> mFinalCantRewardMessage;
    cTkFixedString<512,char> macFinalRewardDescription;
    cTkTextureResource mMainIcon;
    int miSeasonNumber;
    int miRemixNumber;
    int miDisplayNumber;
    TkID<256> mSeasonName;
    TkID<256> mSeasonNameUpper;
    TkID<256> mMainMissionTitle;
    TkID<256> mMainMissionMessage;
    bool mbDoCommunityMissionTextSubstitutions;
    bool mbDefaultToPvPOff;
    bool mbMustCraftInBases;
    cTkDynamicArray<TkID<128> > maAdditionalTradeProducts;
    cTkDynamicArray<TkID<128> > maNeverTradeProducts;
    int miStartingSuitSlots;
    int miStartingSuitTechSlots;
    int miStartingSuitCargoSlots;
    cTkSeed mWeaponSeed;
    cTkSeed mShipSeed;
    cGcSpaceshipClasses mShipType;
    bool mbStartWithFreighter;
    cTkFixedString<128,char> macFreighterBaseOverrideFilename;
    cGcAlienRace mFreighterRace;
    bool mbStartAboardFreighter;
    bool mbForceStartSystemTernary;
    bool mbForceStartSystemAbandoned;
    cTkDynamicArray<cGcBuildingClassification> maValidSpawnBuildings;
    cGcInventoryLayout mWeaponInventoryLayout;
    cGcInventoryLayout mShipInventoryLayout;
    cGcInventoryLayout mShipTechInventoryLayout;
    bool mbUseDefaultAppearance;
    cGcInventoryContainer mInventory;
    cGcInventoryContainer mInventory_TechOnly;
    cGcInventoryContainer mInventory_Cargo;
    cGcInventoryContainer mShipInventory;
    cGcInventoryContainer mWeaponInventory;
    bool mbUseRandomPet;
    cTkDynamicArray<cGcSeasonPetConstraints> maRandomPetConstraints;
    cTkFixedArray<cGcPetData> maSpecificPets;
    cTkDynamicArray<cGcSandwormTimerAndFrequencyOverride> maSandwormOverrides;
    bool mbSandwormGlobalOverride;
    float mfSandwormGlobalOverrideTimer;
    float mfSandwormGlobalOverrideSpawnChance;
    bool mbStartNextToShip;
    float mfDistanceFromShipAtStartOfGame;
    bool mbShipStartsDamaged;
    bool mbAllowMissionDetailMessages;
    bool mbUseStartPlanetObjectListOverrides;
    TkID<128> mStartPlanetRareSubstanceOverride;
    bool mbTrashInventoryOnGalaxyTravel;
    int miFreighterBattleEarlyWarpsOverride;
    bool mbForceDeepSpaceAmbientFrigatesOnInfested;
    int miTechCostMultiplier;
    cTkDynamicArray<TkID<128> > maNeverLearnableTech;
    cTkDynamicArray<TkID<128> > maForgottenProducts;
    bool mbIncreaseXClassTechOddsWithCommTier;
    float mfAbandonedFreighterHazardProtectionMul;
    float mfHazardProtectionDrainMultiplier;
    float mfEnergyDrainMultiplier;
    int miQuestSubstanceReducer;
    cTkDynamicArray<cGcSeasonalStage> maStages;
    cGcScanEventTable mScanEventTable;
    bool mbResetSaveOnDeath;
    cTkDynamicArray<cGcPersistedStatData> maStatsToPersistOnReset;
    bool mbCompatibleWithState;
    bool mbHasBeenConverted;
    cTkDynamicArray<cGcTechnology> maTechnologyTable;
    cTkDynamicArray<cGcProductData> maProductTable;
    cTkDynamicArray<cGcRealitySubstanceData> maSubstanceTable;
    cGcTradeData mSeasonalUAStationTradeData;
    bool mbUseSeasonalUAStationTradeData;

    static bool ClassPointerCompare(const cTkClassPointer* lPtr, const cTkClassPointer *lOtherPtr);
    static void ClassPointerCopy(cTkClassPointer* lDest, const cTkClassPointer *lSource);
    static cTkClassPointer* ClassPointerCreate(cTkClassPointer* result);
    static void ClassPointerCreateDefault(cTkClassPointer* lPtr, cTkLinearMemoryPool* lpAllocator);
    static void ClassPointerDestroy(cTkClassPointer* lPtr);
    static void ClassPointerValidateData(cTkClassPointer* lPtr);
    static unsigned __int64 ClassPointerGenerateHash(const cTkClassPointer* lPtr, unsigned __int64 luHash, bool lbDeep);
    static void ClassPointerRead(cTkClassPointer* lPtr, XMLNode* lDataNode, cTkLinearMemoryPool* lpAllocator);
    static void ClassPointerRender(cTkClassPointer* lPtr);
    static bool ClassPointerSave(const cTkClassPointer* lPtr, const char* lpacFilename);
    static void ClassPointerWrite(const cTkClassPointer* lPtr, XMLNode* lDataNode, bool lbForceShortForm);
};
