#pragma once

#include "../../../../../../pch.h"
class cGcSubstanceSecondaryBiome;
class cGcRealityIconTable;
class cGcTechList;
class cGcTradeSettings;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcInventoryLayout;
class cGcInventoryLayout;

class cGcRealityManagerData
{
    static const unsigned __int64 muNameHash = 6426729213987279657;
    static const unsigned __int64 muTemplateHash = 14996579099529455348;
    static const int miNumMembers = 80;

    unsigned __int16 muiHomeRealityIteration;
    unsigned __int16 muiRealityIteration;
    cTkFixedArray<cGcDiscoveryWorth> maDiscoveryWorth;
    cTkFixedArray<float> maCreatureDiscoverySizeMultiplier;
    cTkDynamicArray<cGcSubstanceSecondaryLookup> maSubstanceSecondaryLookups;
    cGcSubstanceSecondaryBiome mSubstanceSecondaryBiome;
    cTkFixedString<128,char> macTechnologyTable;
    cTkFixedString<128,char> macSubstanceTable;
    cTkFixedString<128,char> macProductTable;
    cTkFixedString<128,char> macProceduralProductTable;
    cTkFixedString<128,char> macProceduralTechnologyTable;
    cTkFixedString<128,char> macLegacyItemConversionTable;
    cTkDynamicArray<cTkRawID> maLegacyRepairTable;
    cTkFixedString<128,char> macConsumableItemTable;
    cTkFixedString<128,char> macRecipeTable;
    cTkFixedString<128,char> macStoriesTable;
    cTkFixedString<128,char> macDialogClearanceTable;
    cTkFixedString<128,char> macAlienWordsTable;
    cTkDynamicArray<cTkFixedString<128,char> > maAlienPuzzleTables;
    cTkFixedArray<bool> maLoopInteractionPuzzles;
    cTkFixedArray<cGcAlienPuzzleTableIndex> maInteractionPuzzlesIndexTypes;
    cTkFixedArray<cTkCurveType> maWeightingCurves;
    cTkDynamicArray<cGcDamageMultiplierLookup> maDamageMultiplierTable;
    cTkFixedString<128,char> macRewardTable;
    cTkFixedString<128,char> macDiscoveryRewardTable;
    cTkFixedString<128,char> macInventoryTable;
    cTkFixedString<128,char> macDamageTable;
    cTkFixedString<128,char> macPurchaseableBuildingBlueprintsTable;
    cTkFixedString<128,char> macPurchaseableSpecialsTable;
    cTkFixedString<128,char> macUnlockableSeasonRewardsTable;
    cTkFixedString<128,char> macUnlockableTwitchRewardsTable;
    cTkFixedString<128,char> macUnlockablePlatformRewardsTable;
    cTkFixedString<128,char> macCostTable;
    cTkFixedString<128,char> macTradingCostTable;
    cTkFixedString<128,char> macTradingClassDataTable;
    cTkFixedString<128,char> macMaintenanceGroupsTable;
    cTkFixedString<128,char> macUnlockableItemTrees;
    cTkFixedString<128,char> macSettlementPerksTable;
    cTkFixedString<128,char> macPlayerWeaponPropertiesTable;
    cTkFixedString<128,char> macCombatEffectsTable;
    cTkFixedString<128,char> macTechBoxTable;
    cTkDynamicArray<cGcFreighterCargoOption> maFreighterCargoOptions;
    cTkFixedArray<cGcShipWeaponData> maShipWeapons;
    cTkFixedArray<cGcPlayerWeaponData> maPlayerWeapons;
    cTkFixedArray<cTkIdArray> maDefaultVehicleLoadout;
    cTkFixedArray<TkID<128> > maFactionStandingIDs;
    cTkFixedArray<TkID<256> > maFactionNames;
    cTkFixedArray<cGcNumberedTextList> maFactionClients;
    cTkFixedArray<cGcNumberedTextList> maMissionNameFormats;
    cTkFixedArray<cGcNumberedTextList> maMissionNameAdjectives;
    cTkFixedArray<cGcNumberedTextList> maMissionNameNouns;
    cTkFixedArray<cTkIdArray> maMissionBoardRewardOptions;
    cTkFixedArray<float> maWeightedTextWeights;
    cGcRealityIconTable mIcons;
    cTkFixedArray<cTkColour> maHazardColours;
    cTkFixedArray<cTkColour> maRarityColours;
    cTkFixedArray<cTkColour> maSubstanceCategoryColours;
    cTkFixedArray<cTkTextureResource> maSubstanceChargeIcons;
    cTkFixedArray<cTkTextureResource> maStatCategoryIcons;
    cTkFixedArray<cTkTextureResource> maStatTechPackageIcons;
    cTkFixedArray<cGcStats> maStats;
    cGcTechList mStationTechShops;
    cTkFixedArray<cGcTechList> maPlanetTechShops;
    cGcTradeSettings mTradeSettings;
    cTkDynamicArray<TkID<128> > maPirateStationExtraProds;
    cGcInventoryLayout mSuitStartingSlotLayout;
    cGcInventoryLayout mSuitTechOnlyStartingSlotLayout;
    cGcInventoryLayout mSuitCargoStartingSlotLayout;
    cGcInventoryLayout mShipStartingLayout;
    cGcInventoryLayout mShipTechOnlyStartingLayout;
    cGcInventoryLayout mShipCargoOnlyStartingLayout;
    cTkDynamicArray<int> maSuitUpgradePrices;
    cTkDynamicArray<int> maSuitTechOnlyUpgradePrices;
    cTkDynamicArray<int> maSuitCargoUpgradePrices;
    cTkDynamicArray<TkID<128> > maNeverSellableItems;
    cTkDynamicArray<TkID<128> > maNeverOfferedForSale;
    cTkFixedArray<float> maNormalisedPriceLimits;
    cTkDynamicArray<cGcFiendCrimeSpawnTable> maFiendCrimeSpawnTable;
    cTkDynamicArray<cGcIDPair> maFreighterBaseItemPairs;
    cTkFixedArray<cTkFixedString<128,char> > maCatalogues;

    static bool ClassPointerCompare(const cTkClassPointer* lPtr, const cTkClassPointer *lOtherPtr);
    static void ClassPointerCopy(cTkClassPointer* lDest, const cTkClassPointer *lSource);
    static cTkClassPointer* ClassPointerCreate(cTkClassPointer* result);
    static void ClassPointerCreateDefault(cTkClassPointer* lPtr, cTkLinearMemoryPool* lpAllocator);
    static void ClassPointerDestroy(cTkClassPointer* lPtr);
    static void ClassPointerValidateData(cTkClassPointer* lPtr);
    static unsigned __int64 ClassPointerGenerateHash(const cTkClassPointer* lPtr, unsigned __int64 luHash, bool lbDeep);
    static void ClassPointerRead(cTkClassPointer* lPtr, XMLNode* lDataNode, cTkLinearMemoryPool* lpAllocator);
    static void ClassPointerRender(cTkClassPointer* lPtr);
    static bool ClassPointerSave(const cTkClassPointer* lPtr, const char* lpacFilename);
    static void ClassPointerWrite(const cTkClassPointer* lPtr, XMLNode* lDataNode, bool lbForceShortForm);
};
